### PR TITLE
Update README

### LINKED ISSUE #7: 📓 update readme

### PR DESCRIPTION
**Pull request by tyler36**
This PR makes some minor updates to the readme.

- Fix some typos
- Adds links to referenced sites

Fixes #7

### CODE REVIEW

**Comment by tyler36** [comment]
The README also has a section called "Disabling MySQL & MariaSQL"

This addon automatically disables these in its `config.sqlsrv.yaml` so I think we can remove this section or perhaps rework?

**Comment by robertoperuzzo** [comment]
I think we leave some info in the readme about the config.*.yml because someone (like me) may use this add-on to connect to a second external sqlsrv db and not as main Drupal db. What do you think?

**Comment by tyler36** [comment]
@robertoperuzzo 

Sounds reasonable. I think it's confusing that the addon describes how to disable the default database but disables it via a different file.

Perhaps we need something like:

"This addons disables the default database with via the `config.sqlsrv.yaml`"

And move the current instructions into a "Manually disabling the default DDEV database" for people who prefer to manage things themselves.

Does this make sense or am I overthinking things?

**Comment by robertoperuzzo** [comment]
> @robertoperuzzo
> 
> Sounds reasonable. I think it's confusing that the addon describes how to disable the default database but disables it via a different file.
> 
> Perhaps we need something like:
> 
> "This addons disables the default database with via the `config.sqlsrv.yaml`"
> 
> And move the current instructions into a "Manually disabling the default DDEV database" for people who prefer to manage things themselves.
> 
> Does this make sense or am I overthinking things?

It makes sense.

We could replace the paragraph like that:

## Manually enabling MySQL/MariaDB

**This addons disables the default database by automatically adding `omit_containers: [db,dba]` in the `config.sqlsrv.yaml`**

If your project needs to use both MariaDB and MS SQL Server databases, you have to remove `#ddev-generated` and 
`omit_containers: [db,dba]` from `config.sqlsrv.yaml`.

See [.ddev/config.yaml Options](https://ddev.readthedocs.io/en/stable/users/extend/config_yaml/) for additional notes.

**Comment by tyler36** [comment]
That looks better to me. 

Not sure if you want to update this PR or open a new one.

**Pull request merged**
